### ISSUE TITLE
catkin_make during the Install script run

### ISSUE THREAD

**Issue by bajo** [squirrel-project/squirrel_recommender#12]
There are ROS related issues with the install scripts. During the catkin_make install in   squirrel_robotino_arm/cf_control hardware_interfaceConfig.cmake and thrift are not found. 
Therefore the catkin_make fails. 

Not really the fault of the install scripts, but we need to fix this at some point.

**Comment by NadiaHG** [comment]
it is a squirrel_robotino_arm issue, but the plan is not use the cf_control after next week

**Comment by bajo** [comment]
I thought so. Thanks for clarifying. :)

**Comment by NadiaHG** [comment]
out-of-date
