### ISSUE TITLE
Driver startup with Upstart installation

### ISSUE THREAD

**Issue by ghost** [squirrel-project/squirrel_recommender#25]
Hi,

I noticed the following misbehavior on our robot (ALUFR-robotino) related to the upstart installation. We did the following:
1. Setup the upstart installation as described in the readme.
2. Changed `/etc/ros/indigo/robotino.d/launch/robot/robot.launch` file so that `squirrel_control.launch` is run on startup.

What happens is that the arm controllers crash whenever the robot is freshly booted (robot switched on), most likely because the arm driver are not booted yet. Indeed, the issue does not occur whe the robot rebooted w/o switching it off. 

I guess this could be fixed by checking whether the arm drivers are on or just setting a sleeping time before  launching the ros stuff at startup.

**Comment by NadiaHG** [comment]
the cleanest solution will be that the driver wait to start the controllers until the arm is booted. But if it is too much effort just add a sleep before the rolaunch (line 70) in the robotino-start file: https://github.com/squirrel-project/squirrel_recommender/blob/master/setup_robotino/upstart/robotino-start#L70

**Comment by ghost** [comment]
I added 30s sleep before launching the ros stack. It worked. I think the issue can be closed.

**Comment by NadiaHG** [comment]
Please close the issue if https://github.com/squirrel-project/squirrel_recommender/pull/26 is right
