### ISSUE TITLE
Needs update?

### ISSUE THREAD

**Issue by bajo** [squirrel-project/squirrel_recommender#30]
https://github.com/squirrel-project/squirrel_recommender/blob/5b86d297366d54321da20f330f3b1ac2aab8c3f5/setup_robotino/robotino-adduser#L19
@ipa-nhg Do we need to update this line, as we no longer are on robotino?

**Comment by NadiaHG** [comment]
I think it is correct, you call rsync from scrat (where you call locally the adduser) https://github.com/squirrel-project/squirrel_recommender/blob/5b86d297366d54321da20f330f3b1ac2aab8c3f5/setup_robotino/robotino-adduser#L3  to robotino pc, adding the new user also for robotino. Please test on your robot `robotino-adduser test` and try to login with the test user on robotino pc.
